# Generated by Django 2.1 on 2018-08-26 08:47

import devices.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('application/json', 'JSON'), ('application/octet-stream', 'BINARY'), ('text/plain', 'PLAINTEXT')], default=devices.utils.PropertyTypes('application/octet-stream'), max_length=9)),
                ('content_data', models.BinaryField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='devices.Device')),
            ],
        ),
    ]
